//! task.rs
//!
//! Defines the `Task` struct and the physics-based deadline model
//! (Time-To-Collision, TTC) described in the project spec, plus the
//! Laxity / Relaxation(R) metric used by the proposed scheduler.

use serde::Serialize;

/// Discrete weather conditions, each carrying its own lambda (brake
/// effectiveness penalty) as specified in the project document:
///   sunny = 0.0, rainy = 0.3, snowy = 0.6
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum Weather {
    Sunny,
    Rainy,
    Snowy,
}

impl Weather {
    /// lambda: models the effect of weather on braking power.
    pub fn lambda(&self) -> f64 {
        match self {
            Weather::Sunny => 0.0,
            Weather::Rainy => 0.3,
            Weather::Snowy => 0.6,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Weather::Sunny => "sunny",
            Weather::Rainy => "rainy",
            Weather::Snowy => "snowy",
        }
    }

    pub fn all() -> [Weather; 3] {
        [Weather::Sunny, Weather::Rainy, Weather::Snowy]
    }
}

/// Priority levels: 1 = highest priority, 5 = lowest, matching the spec.
pub type Priority = u8;

/// A single aperiodic task as generated by the simulator.
///
/// Time units are abstract "ticks"; per the spec, 1 tick = 10ms of
/// real-world time. All time-valued fields (arrival, deadline,
/// execution time, timestamps) are expressed in ticks unless noted.
#[derive(Debug, Clone, Serialize)]
pub struct Task {
    pub id: usize,

    /// Time at which the task arrives in the system (ready to be
    /// considered), drawn uniformly from [0, 30].
    pub arrival_time: f64,

    /// Worst-case / nominal execution time in ticks, drawn uniformly
    /// from [1, 13].
    pub execution_time: f64,

    /// Remaining execution time; mutated as the simulation advances.
    /// Starts equal to `execution_time`.
    pub remaining_time: f64,

    /// Priority in {1,2,3,4,5}, 1 = highest.
    pub priority: Priority,

    /// Randomly sampled obstacle distance in meters, used only as an
    /// input to the deadline (TTC) calculation. Drawn uniformly from
    /// [50, 150].
    pub obstacle_distance: f64,

    /// Absolute deadline in ticks = arrival_time + TTC.
    pub deadline: f64,

    // --- Bookkeeping fields populated during simulation ---
    pub start_time: Option<f64>,
    pub finish_time: Option<f64>,
    pub dropped: bool,
    pub dropped_at: Option<f64>,
    pub context_switches_incurred: u32,
    pub completed: bool,
}

/// Physical constants from the spec.
pub const V0: f64 = 30.0; // initial vehicle speed, m/s
pub const A: f64 = 5.0; // braking deceleration, m/s^2

/// Computes Time-To-Collision (TTC) given an effective obstacle
/// distance and a weather-dependent lambda, following:
///
///     TTC = (v0 - sqrt(v0^2 - 2*a*(1-lambda)*d)) / (a*(1-lambda))
///
/// IMPLEMENTATION NOTE (flagged ambiguity #1 — see project plan):
/// The source document does not give an explicit formula for how the
/// `Deadline Tightness` coefficient (range [0.5, 2.46]) is meant to
/// enter this equation. We adopt the interpretation that Tightness
/// scales the *effective obstacle distance* inversely:
///
///     d_effective = d / tightness
///
/// Rationale: higher tightness => shorter effective distance => lower
/// TTC => tighter (sooner) deadline, which matches the document's
/// description of tightness as "how strict deadlines are." This is
/// our chosen convention, not a value taken from the spec — confirm
/// with the TA and adjust `effective_distance()` below if a different
/// mapping is intended (e.g. scaling `a` or scaling the final TTC
/// directly).
///
/// IMPLEMENTATION NOTE (domain-validity guard):
/// If `v0^2 - 2*a*(1-lambda)*d < 0`, the square root is undefined,
/// i.e. the vehicle cannot collide with the obstacle at all under the
/// given braking assumptions (it stops in time even with zero
/// reaction delay). We treat this case as "no collision risk" and
/// fall back to a documented constant TTC (see `FALLBACK_TTC`) rather
/// than an unusable infinite deadline. This clamping choice is also a
/// documented assumption.
pub fn effective_distance(obstacle_distance: f64, tightness: f64) -> f64 {
    obstacle_distance / tightness
}

/// Returns `None` if the term under the square root is negative
/// (no physically meaningful collision time), `Some(ttc)` otherwise.
pub fn time_to_collision(d_effective: f64, lambda: f64) -> Option<f64> {
    let denom = A * (1.0 - lambda);
    if denom <= 0.0 {
        // (1 - lambda) should always be > 0 given lambda in {0.0,0.3,0.6},
        // but guard defensively against degenerate inputs.
        return None;
    }
    let under_sqrt = V0 * V0 - 2.0 * denom * d_effective;
    if under_sqrt < 0.0 {
        return None;
    }
    let ttc = (V0 - under_sqrt.sqrt()) / denom;
    Some(ttc)
}

/// Fallback TTC (in ticks) used when the discriminant in the TTC
/// formula is negative, i.e. no real collision is imminent. Chosen
/// to be comfortably larger than the max possible "normal" TTC so
/// such tasks are deprioritized but not nonsensical. Documented
/// assumption — adjust if the TA specifies a different convention.
pub const FALLBACK_TTC: f64 = 50.0;

/// Computes the absolute deadline for a task given its arrival time,
/// obstacle distance, the current weather, and the deadline-tightness
/// coefficient.
pub fn compute_deadline(
    arrival_time: f64,
    obstacle_distance: f64,
    weather: Weather,
    tightness: f64,
) -> f64 {
    let d_eff = effective_distance(obstacle_distance, tightness);
    let ttc = time_to_collision(d_eff, weather.lambda()).unwrap_or(FALLBACK_TTC);
    arrival_time + ttc
}

impl Task {
    /// Laxity at current time `t`:
    ///     Laxity = Deadline - t - RemainingExecutionTime
    pub fn laxity(&self, t: f64) -> f64 {
        self.deadline - t - self.remaining_time
    }
}

/// theta(lambda) = 1.5 + lambda, the "environment adaptation
/// coefficient" from the spec.
pub fn theta(lambda: f64) -> f64 {
    1.5 + lambda
}

/// Computes normalized Laxity (`L_norm`) for every task currently in
/// the ready queue, using min-max scaling **within that queue at this
/// instant only** (per the spec: "only among tasks in the queue at
/// that moment"). Returns a vector aligned by index with the input
/// slice.
///
/// If all laxities in the queue are equal (max == min), every
/// normalized value is defined as 0.5 (a neutral mid-point) to avoid
/// division by zero.
pub fn normalize_laxities(laxities: &[f64]) -> Vec<f64> {
    if laxities.is_empty() {
        return vec![];
    }
    let min_l = laxities.iter().cloned().fold(f64::INFINITY, f64::min);
    let max_l = laxities.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let range = max_l - min_l;
    if range.abs() < 1e-9 {
        return vec![0.5; laxities.len()];
    }
    laxities.iter().map(|l| (l - min_l) / range).collect()
}

/// Relaxation metric:
///     R_i(lambda) = theta(lambda) * L_norm(i) + P_i
///
/// Lower R => scheduled sooner (per spec: queue sorted ascending by R).
pub fn relaxation(theta_val: f64, l_norm: f64, priority: Priority) -> f64 {
    theta_val * l_norm + priority as f64
}
